# Generated by Django 4.2.7 on 2023-11-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('usertype', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=64)),
                ('teacher_email', models.EmailField(max_length=64, unique=True)),
                ('teacher_phone', models.IntegerField()),
                ('teacher_qualification', models.CharField(max_length=64)),
                ('teacher_department', models.CharField(max_length=64)),
                ('teacher_gender', models.CharField(max_length=64)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
            ],
        ),
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('student_email', models.EmailField(max_length=64, unique=True)),
                ('student_phone', models.IntegerField()),
                ('student_course', models.CharField(max_length=64)),
                ('student_department', models.CharField(max_length=64)),
                ('student_gender', models.CharField(max_length=64)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
            ],
        ),
    ]
